config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  root :to => 'home#show'


  get 'login' => 'user_sessions#new', :as => :login
  post 'login' => "user_sessions#create"
  post 'logout' => 'user_sessions#destroy', :as => :logout
  
  get 'dashboard' => "dashboard#show", :as => :dashboard

  resources :user_sessions
  resources :users do
    member do
      get :activate
    end
  end

  resources :password_resets, only: [:new, :create, :edit, :update]
  
  resources :things
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/thing.rb
class Thing < ApplicationRecord

    validates :name, presence: true

end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_action :set_thing, only: %i[ show edit update destroy ]

  # GET /things or /things.json
  def index
    @things = policy_scope(Thing.all)
  end

  # GET /things/1 or /things/1.json
  def show
  end

  # GET /things/new
  def new
    @thing = authorize Thing.new
  end

  # GET /things/1/edit
  def edit
  end

  # POST /things or /things.json
  def create
    @thing = authorize Thing.new(thing_params)

    respond_to do |format|
      if @thing.save
        format.html { redirect_to thing_url(@thing), notice: "Thing was successfully created." }
        format.json { render :show, status: :created, location: @thing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /things/1 or /things/1.json
  def update
    respond_to do |format|
      if @thing.update(thing_params)
        format.html { redirect_to thing_url(@thing), notice: "Thing was successfully updated." }
        format.json { render :show, status: :ok, location: @thing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /things/1 or /things/1.json
  def destroy
    @thing.destroy

    respond_to do |format|
      format.html { redirect_to things_url, notice: "Thing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thing
      @thing = authorize Thing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def thing_params
      params.require(:thing).permit(:name, :description)
    end
    
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/things/_form.html.erb
<%= simple_form_for(@thing) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <%= f.input :name %>
  <%= f.input :description %>

  <%= f.button :submit, class: "btn-primary" %>
  <%= link_to "Cancel", :back, class: "btn btn-outline-secondary" %>

<% end %>

app/views/things/_thing.html.erb
<div id="<%= dom_id thing %>">
  <p>
    <strong>Name:</strong>
    <%= thing.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= thing.description %>
  </p>

</div>

app/views/things/edit.html.erb
<h1>Editing thing</h1>

<%= render partial: "form", layout: "card_form", thing: @thing, locals: { title: "Editing thing" } %>

<br>

<div>
  <%= link_to "Show this thing", @thing %> |
  <%= link_to "Back to things", things_path %>
</div>



<% content_for :toolbar do %>
  <li class="nav-item">
    <%= link_to "Things", things_path, class: "nav-link" %>
  </li>

  <li class="nav-item">
    <%= link_to "New thing", new_thing_path, class: "nav-link" %>
  </li>
<% end %>

app/views/things/index.html.erb
<h1>Things</h1>

<div class="row" id="things">

  <% @things.each do |thing| %>
    <div class="col-sm-3">

      <%= link_to thing do %>

        <div class="card" id="<%= dom_id thing %>">
          <div class="card-body">
            <h5 class="card-title"><%= thing.name %></h5>
            <h6 class="card-subtitle mb-2 text-muted"><%= thing.description %></h6>
          </div>
        </div>

    <% end %>  

    </div>
  <% end %>
</div>


<% content_for :toolbar do %>
  <li class="nav-item">
    <%= link_to "New thing", new_thing_path, class: "nav-link" %>
  </li>

<% end %>

app/views/things/new.html.erb
<h1>New thing</h1>

<%= render partial: "form", layout: "card_form", object: @thing, locals: { title: "Vertical Form" } %>

<br>

<% content_for :toolbar do %>
  <li class="nav-item">
    <%= link_to "Things", things_path, class: "nav-link" %>
  </li>
<% end %>

app/views/things/show.html.erb
<%= render @thing %>

<div>
</div>

<% content_for :toolbar do %>
  <li class="nav-item">
    <%= link_to "Things", things_path, class: "nav-link" %>
  </li>

  <li class="nav-item">
    <%= link_to "Edit Thing", edit_thing_path(@thing), class: "nav-link" %> 
  </li>

  <%= button_to "Delete Thing", @thing, method: :delete, class: "btn btn-link nav-link" %>

  <li class="nav-item">
    <%= link_to "New Thing", new_thing_path, class: "nav-link" %> 
  </li>


  
<% end %>