config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  root :to => 'home#show'


  get 'login' => 'user_sessions#new', :as => :login
  post 'login' => "user_sessions#create"
  post 'logout' => 'user_sessions#destroy', :as => :logout
  
  get 'dashboard' => "dashboard#show", :as => :dashboard

  resources :user_sessions
  resources :users do
    member do
      get :activate
    end
  end

  resources :password_resets, only: [:new, :create, :edit, :update]
  
  resources :things
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user_session.rb
class UserSession
    include ActiveModel::Model

    attr_accessor :email, :password
    validates :email, :password, presence: true

    def persisted?
        false
    end

end

app/controllers/user_sessions_controller.rb
# app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  layout "public"
  skip_before_action :require_login, only: [:new, :create]

  # GET /users_sessions/new
  def new
    @user_session = authorize UserSession.new
  end

  # POST /user_sessions or /user_sessions.json
  def create
    @user_session = authorize UserSession.new(user_session_params)
    if @user_session.valid?
      @user = login(@user_session.email, @user_session.password) 
      @user_session.errors.add :base, :invalid, message: "Invalid username or password, login denied" unless @user
    end

    respond_to do |format|
      if @user
        format.html { redirect_back_or_to(:dashboard, notice: 'Login successful')}
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_session.errors, status: :unprocessable_entity }
      end
    end
  end

  def old_create
    @user = login(params[:email], params[:password])

    if @user
      redirect_back_or_to(:dashboard, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new', status: :unprocessable_entity
    end
  end

  def destroy
    authorize UserSession
    logout
    redirect_to(:root, notice: 'Logged out!')
  end

private

    # Only allow a list of trusted parameters through.
    def user_session_params
        params.require(:user_session).permit(:email, :password)
    end

end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_form.html.erb
<%= simple_form_for(@user_session) do |f| %>
  <%= f.error_notification unless f.object.errors[:base].present? %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <%= f.input :email %>
  <%= f.input :password %>

  <%= f.button :submit, "Login", class: "btn-primary" %>
  <%= link_to "Cancel", :back, class: "btn btn-outline-secondary" %>

<% end %>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<p><%= link_to '< Back', root_path %></p>
<div class="row">
    <div class="col px-5">
        <h1>Login</h1>
        <%= render "form", user_session: @user_session %>
        <p class="my-2"><%= link_to 'Forgotten your password?', new_password_reset_path %></p>
    </div>
    <div class="col px-5 border-start">
        <h1>Register</h1>
        <p>If you don't have a password you will need to register.<p>
        <%= link_to "Register here", new_user_path, class: "btn btn-secondary" %>
    </div>
</div>